<?php
$l_help_title = "Sneltoets Help";
$l_help_subtitle = "De volgende Sneltoetsen zal uitvoeren de volgende opdrachten:";
$l_help_addtraderoute = "Voeg een handelsroutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Baken";
$l_help_genesisdevice = "Genesis apparaat";
$l_help_sectorgenesis = "Sector Genesis";
$l_help_devicemenu = "Device menu";
$l_help_SDreport = "Sector verdediging Verslag";
$l_help_Ewarp = "Emergency Warp";
$l_help_fullLRscan = "Volledige Long Range Scan";
$l_help_galaxymap = "Galaxy Kaart";
$l_help_localmap = "Lokale Galaxy Kaart";

$l_help_IGB = "IGB";
$l_help_log = "Aanmelden";
$l_help_logout = "Afmelden";
$l_help_readmessages = "Lees Berichten";
$l_help_deploymines = "Deploy Mines";
$l_help_news = "Nieuws";
$l_help_sectornotes = "Sector Notes";
$l_help_options = "Opties";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Probe Menu";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Ship Verslag";
$l_help_sendmessage = "Bericht versturen";
$l_help_listTRroutes = "Lijst Trade Routes";
$l_help_teamSD = "Team Sector verdediging";
$l_help_3Dmap = "3D Galaxy Kaart";
$l_help_warpeditor = "Warp-editor";
$l_help_storeshipreport = "Opgeslagen Ship Verslag";
$l_help_dignitarymenu = "Hoogwaardigheidsbekleder Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy Lokaal (nieuw venster)";
?>
