<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "De Melkweg is het sterrenstelsel waar de planeet Aarde en de Federatie is gevestigd";
$l_galaxy_description[2] = "Onontgonnen Galaxy 2";
$l_galaxy_description[3] = "Onontgonnen Galaxy 3";
$l_galaxy_description[4] = "Onontgonnen Galaxy 4";
$l_galaxy_description[5] = "Onontgonnen 5 Galaxy";
$l_galaxy_description[6] = "Onontgonnen Galaxy 6";
$l_galaxy_description[7] = "Onontgonnen Galaxy 7";
$l_galaxy_description[8] = "Onontgonnen Galaxy 8";
$l_galaxy_description[9] = "Onontgonnen Galaxy 9";
$l_galaxy_description[10] = "Onontgonnen Galaxy 10";

?>
