<?php
$l_help_title = "Hotkey Aide";
$l_help_subtitle = "Les touches suivantes seront d&#39;exécuter les commandes suivantes:";
$l_help_addtraderoute = "Ajouter une Routes commerciales";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Balise";
$l_help_genesisdevice = "Dispositif Genesis";
$l_help_sectorgenesis = "Secteur de la Genèse";
$l_help_devicemenu = "Device Menu";
$l_help_SDreport = "Secteur de la défense Rapport";
$l_help_Ewarp = "Warp urgence";
$l_help_fullLRscan = "Long Range Full Scan";
$l_help_galaxymap = "Galaxy Carte";
$l_help_localmap = "Plan Local Galaxy";

$l_help_IGB = "IGB";
$l_help_log = "Connectez-vous";
$l_help_logout = "Déconnexion";
$l_help_readmessages = "Lire les messages";
$l_help_deploymines = "Déployer des mines";
$l_help_news = "Nouvelles";
$l_help_sectornotes = "Secteur Notes";
$l_help_options = "Options";
$l_help_planetreport = "Rapport Planète";
$l_help_probemenu = "Probe Menu";
$l_help_ranking = "Classements";

$l_help_shipreport = "Rapport des navires";
$l_help_sendmessage = "Envoyer un message";
$l_help_listTRroutes = "Liste Routes commerciales";
$l_help_teamSD = "Équipe sectorielle défenses";
$l_help_3Dmap = "Carte 3D Galaxy";
$l_help_warpeditor = "Sous la direction de Warp";
$l_help_storeshipreport = "Stockées Ship Rapport";
$l_help_dignitarymenu = "Dignitaire Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy locales (nouvelle fenêtre)";
?>
