<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "La Voie lactée est la galaxie où la planète Terre et de la Fédération est situé";
$l_galaxy_description[2] = "Inexplorée Galaxy 2";
$l_galaxy_description[3] = "Inexplorée Galaxy 3";
$l_galaxy_description[4] = "Inexplorée Galaxy 4";
$l_galaxy_description[5] = "Inexplorée Galaxy 5";
$l_galaxy_description[6] = "Inexplorée Galaxy 6";
$l_galaxy_description[7] = "Inexplorée Galaxy 7";
$l_galaxy_description[8] = "Inexplorée Galaxy 8";
$l_galaxy_description[9] = "Inexplorée Galaxy 9";
$l_galaxy_description[10] = "Inexplorée Galaxy 10";

?>
