<?php

// Confirmed common to multiple files:

$game_charset = "ISO-8859-1";

$l_zname[1] = "Unchartered rymden";
$l_zname[2] = "Federationens";
$l_zname[3] = "Alliansen rymden";
$l_zname[4] = "Krigszon";

$l_nova = "Nova";
$l_nova = "Nova Bomb";
$l_lssd = "Senast fartyg sett enhet";
$l_lss = "Senast fartyg sett i denna sektor";
$l_galaxy = "Galaxy";
// Common to : warpedit 1-3.php

$l_warp_title = "Använd Warp Editor";
$l_warp_turn = "Du behöver minst en tur att använda en varp editor.";
$l_warp_none = "Du har inga varp redaktörer.";
$l_warp_forbid = "Använda en Warp Editor inom denna sektor är inte tillåten.";
$l_swarp_forbid = "Använda en Warp Editor till eller från SG sektorer är inte tillåtet.";
$l_warp_nosector = "Sektor finns inte.";

// Not yet confirmed common to multiple files:

$l_yes = "Ja";
$l_no = "Nej";
$l_here = "här";
$l_submit = "Skicka in";
$l_reset = "Återställ";
$l_all = "Alla";
$l_max = "Max";

$l_trade = "Handel";
$l_ore = "Ore";
$l_commodity = "Vara";
$l_commodities = "Råvaror";
$l_organics = "Organics";
$l_goods = "Varor";
$l_energy = "Energi";
$l_colonists = "Kolonister";
$l_credits = "Hp";
$l_units = "enheter";
$l_special = "Särskilda";
$l_upgrade_ports = "Uppgraderingar";
$l_device_ports = "Enheter";
$l_spacedock = "Spacedock";
$l_casino = "Casino";
$l_dig = "Dignitärer";
$l_spy = "Spioner";
$l_wormhole = "Maskhål";

$l_cargo = "Cargo";
$l_fighters = "Fighters";
$l_mines = "Mines";
$l_torps = "Torpeder";

$l_none = "Ingen";
$l_unnamed = "Namnlös";
$l_name = "Namn";
$l_unowned = "Ägarlösa";
$l_unknown = "Okänd";
$l_clickme = "Klicka här";
$l_player = "Spelare";
$l_ship = "Fartyg";
$l_ships = "Fartyg";
$l_set = "ange";
$l_realspace = "Realspace";
$l_armorpts = "Armor poäng";
$l_links = "Länkar";
$l_login_email = "E-postadress:";
$l_add = "Lägg till";
$l_teamforum = "Team Forum";
$l_teamships = "Team Fartyg";
$l_tutorial = "Tutorial / Hjälp";
$l_avatar = "Avatar";
$l_teamicon = "Team Icon";
$l_debris = "Skräp";
$l_localmap = "Lokala Karta";
$l_arm_weap = "Rustning och vapen";
$l_3dmap = "3D Galaxy Karta";

$l_sectormissile = "Sektor Missile";
$l_spacebeacon = "Space Beacon";
$l_spaceprobes = "Rymdsonder";
$l_warpeditors = "Warp Redaktion";
$l_genesistorps = "Genesis Torpeder";
$l_sgtorps = "SG Torpeder";
$l_minesfighters = "Mines / Fighters";
$l_ewarp = "Akut Warp";
$l_reports = "Rapporter";
$l_shipinfo = "Ship Info";
$l_sectornotes = "Sektor Notes";
$l_maps = "Kartor";
$l_messages = "Meddelanden";
$l_shiptype = "Fartygstyp";
$l_help = "Hjälp";
$l_rank = "Rank";

$l_teamplanets = "Team Planets";
$l_teamdefenses = "Team försvar";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet försvar";
$l_changeproduction = "Ändra Production";
$l_galacticarm = "Galactic Arm";

$l_armor = "Armor";
$l_news_none = "Tyvärr, inga nyheter idag.";

$l_ranks_good = "Bra";
$l_ranks_evil = "Ond";
$l_ranks_neutral = "Neutral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zonen är nu en krigszon!";
$l_global_nzone = "Zon är en neutral zon.";
$l_global_team = "Zon tillhör nu gruppen";
$l_global_player = "Zon tillhör nu spelare";
$l_global_nochange = "Zon ägande förändrades inte";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Spaceman Rekrytera";
$l_insignia_name[1] = "Spaceman Apprentice";
$l_insignia_name[2] = "Spaceman";
$l_insignia_name[3] = "Petty Officer tredje klass";
$l_insignia_name[4] = "Petty Officer Second Class";
$l_insignia_name[5] = "ÖVERFURIR";
$l_insignia_name[6] = "FANJUNKARE";
$l_insignia_name[7] = "Senior Chief Petty Officer";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Ensign";
$l_insignia_name[10] = "Löjtnant Junior Grade";
$l_insignia_name[11] = "Löjtnant";
$l_insignia_name[12] = "Örlogskapten";
$l_insignia_name[13] = "Commander";
$l_insignia_name[14] = "Kapten";
$l_insignia_name[15] = "Konteramiral (nedre delen)";
$l_insignia_name[16] = "Konteramiral (övre halvan)";
$l_insignia_name[17] = "Viceamiral";
$l_insignia_name[18] = "Amiral";
$l_insignia_name[19] = "Amiral";

$l_main_title = "Huvudmenyn";
$l_main_warpto = "Warp till";
$l_main_autoroute = "Autoroute till";
$l_main_rs_to = "RSMove till";
$l_main_other = "Annan";
$l_main_shipyard1 = "Varv";
$l_main_shipyard2 = "Öppna";
$l_traderoutes = "Handelsvägar";
$l_trade_control = "Kontroll av handeln";
$l_youhave = "Ni";
$l_turns_used = "Turns används:";
$l_turns_have = "Turns tillgängliga:";
$l_score = "Betyg:";
$l_sector = "Sektor";
$l_help = "Hjälp";
$l_faq = "Frågor och svar";
$l_feedback = "Feedback";
$l_forums = "Forum";
$l_logout = "Logga ut";
$l_commands = "Kommandon";
$l_command_no = "Kommando finns inte.";
$l_devices = "Enheter";
$l_planets = "Planets";
$l_log = "Logga";
$l_sector_def = "Sector försvar";
$l_defense = "Försvar";
$l_read_msg = "Läs meddelanden";
$l_send_msg = "Skicka meddelanden";
$l_rankings = "Rankings";
$l_teams = "Team";
$l_ohno = "Självförstörande";
$l_options = "Alternativ";
$l_navcomp = "Nav Dator";
$l_incompletemove = "Du har inte avslutat din föregående drag.";
$l_clicktocontinue = "Klicka här för att fortsätta";
$l_toplanetmenu = "att åka till planeten menyn.";
$l_nonexistant_pl = "På en icke-existerande planeten???";
$l_abord = ", Ombord på";
$l_messages_wait = "Meddelanden som väntar på dig.";
$l_no_warplink = "Ingen varp länkar";
$l_scan = "Scan";
$l_fullscan = "Fullständig genomsökning";
$l_port = "Port";
$l_tradingport = "Hamnstad";
$l_planet_in_sec = "Planeterna i sektorn";
$l_ships_in_sec = "Andra fartyg i området";
$l_sector_0 = "Det är så mycket trafik i Sol som du inte ens kan isolera andra fartyg!";
$l_map = "Karta";
$l_probe = "Prober";
$l_onboard = "ombord på";
$l_classship = "class fartyg";
$l_traveled = "reste till sektor";
$l_max_planets = "Högsta habital planeter";
$l_block_msg = "Blockera meddelanden";
$l_sectorinfo = "Sektor Info";
$l_add_note = "Lägg till anteckning";
$l_view_note = "Visa";
$l_notes = "Notes";
$l_global_limitreached = "Du har nått gränsen för hur länge du får vara online varje dag. Logga in igen imorgon efter midnatt.";
$l_onlinetimeleft = "Återstående tid:";
$l_planetmax = "Planetary Max:";
$l_storedshipreport = "Lagrade Fartyg";
$l_global_chat = "Global Chat";
$l_team_chat = "Team Chat";
$l_fedinfo = "Federationen Information Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Föregående Sida";
$l_common_next = "Nästa sida";
$l_common_totalpages = "Summa Sidor";
$l_common_selectpage = "Välj sida:";
$l_common_page = "Sida:";
$l_templatechange = "Vill du behålla den här mallen?";

$l_im_fed_bounty = "Förbundet har placerat en bounty på dig för att attackera så lågt rankad spelare. Förbundet kommer att attackera ditt skepp med jämna mellanrum tills du betalar tillbaka din gåva. Du kan betala dina skottpengar på varje uppgradering Port eller Spacedock.";
$l_im_fed_bounty_title = "Federation placerat en bounty på dig!";
$l_im_alliance_bounty = "Alliansen har placerat en bounty på dig för att attackera så lågt rankad spelare. Alliansen kommer att attackera ditt skepp med jämna mellanrum tills du betalar tillbaka din gåva. Du kan betala dina skottpengar på varje uppgradering Port eller Spacedock.";
$l_im_alliance_bounty_title = "Alliance placerat en bounty på dig!";
$l_instant_messages_waiting = "Du har [count] meddelanden som väntar på dig.";

$l_home_planet = "Hemplanet";

$l_hold_space_used = "Rymmer Fyllda:";
$l_hold_space_free = "Rymmer Tom:";
$l_port_buys = "Port Buys:";
$l_port_sells = "Port Sells:";
$l_port_quantity = "Antal:";
$l_port_price = "Pris:";

$l_shoutbox = "Banner_klimatshop";
$l_selectautoroute = "Välj Autoroute";
$l_profiles = "Profiler";
$l_public = "Allmänheten?";
$l_RStolastsector = "Realspace to Last Sector";
$l_RSturns = "Realspace Sätter";

$l_playeroutoftime = "Du har [time] minuter per dag av spelet. Du har använt all din tid för idag. Du kommer att vara i Chat lobbyn för [hours] timmar och [minutes] minuter. Du kommer att tillåtas att fortsätta spela när spelet återställs online-tid för alla spelare.";

$l_casino_description = "Kasinot hamnar alla ägs av alliansen. Förbundet har ingen kontroll över dessa områden. Du kan hitta spel och en Galaxy Wide anslagstavla kallas &quot;The Smugglers Den&quot;. Allt postat i en Smugglers Den kan ses i alla Smugglers Dens överallt och i alla galaxen.";
$l_upgrades_description = "Bli Hamnar är där kan du köpa tech uppgraderingar för fartyget du håller på lotsning.";
$l_device_description = "Device Hamnar är där du kan köpa enheter som vågor, Spies, etc. för fartyget du håller på lotsning.";
$l_spacedock_description = "Spacedocks är där man kan reparera skador på din nuvarande lotsade fartyget.";
$l_none_description = "Denna sektor innehåller inga hamnar.";
$l_infoport_description = "Förbundet Info Port är där du kan hitta användbar information om att flytta runt galaxer och styrningen ditt skepp. Nyheter Meddelanden från förbundet kommer att läggas upp för alla att se ibland. Förbundet Info Port alltid ligger i Sol sektor.";

$l_autoroutelist = "Route till Sector";
$l_mininavinfo = "Klicka Sektor att lagra namn i Warp / Realspace rutan. Klicka W för att hitta AutoRoute och förvränga, Gå till Realspace eller? att kontrollera Realspace svängar.";

$l_noroutetosectortitle = "Ingen rutt";
$l_noroutetosectorbody = "Kan inte hitta en väg till sektorn.";

?>
