<?php
$l_help_title = "Hotkey Hjälp";
$l_help_subtitle = "Följande snabbtangenter kommer att köra följande kommandon:";
$l_help_addtraderoute = "Lägg till en traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Beacon";
$l_help_genesisdevice = "Genesis Device";
$l_help_sectorgenesis = "Sektor Genesis";
$l_help_devicemenu = "Enhetens meny";
$l_help_SDreport = "Sector försvar Report";
$l_help_Ewarp = "Akut Warp";
$l_help_fullLRscan = "Full Long Range Scan";
$l_help_galaxymap = "Galaxy Karta";
$l_help_localmap = "Lokala Galaxy Karta";

$l_help_IGB = "IGB";
$l_help_log = "Logga";
$l_help_logout = "Logga ut";
$l_help_readmessages = "Läs meddelanden";
$l_help_deploymines = "Distribuera Mines";
$l_help_news = "Nyheter";
$l_help_sectornotes = "Sektor Notes";
$l_help_options = "Alternativ";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Probe Meny";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Ship Rapport";
$l_help_sendmessage = "Skicka meddelande";
$l_help_listTRroutes = "Lista handelsvägar";
$l_help_teamSD = "Team Sector försvar";
$l_help_3Dmap = "3D Galaxy Karta";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Lagrade Ship Report";
$l_help_dignitarymenu = "Dignitär Meny";
$l_help_spymenu = "Spy Meny";
$l_help_galaxylocalwindow = "Galaxy Lokalt (nytt fönster)";
?>
