<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Vintergatan är den galax där planeten jorden och federationen är beläget";
$l_galaxy_description[2] = "Outforskat Galaxy 2";
$l_galaxy_description[3] = "Outforskat Galaxy 3";
$l_galaxy_description[4] = "Outforskat Galaxy 4";
$l_galaxy_description[5] = "Outforskat Galaxy 5";
$l_galaxy_description[6] = "Outforskat Galaxy 6";
$l_galaxy_description[7] = "Outforskat Galaxy 7";
$l_galaxy_description[8] = "Outforskat Galaxy 8";
$l_galaxy_description[9] = "Outforskat Galaxy 9";
$l_galaxy_description[10] = "Outforskat Galaxy 10";

?>
