<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Linnutee galaktika, kus planeedi Maa ja Föderatsiooni asub";
$l_galaxy_description[2] = "Uurimata Galaxy 2";
$l_galaxy_description[3] = "Uurimata Galaxy 3";
$l_galaxy_description[4] = "Uurimata Galaxy 4";
$l_galaxy_description[5] = "Uurimata Galaxy 5";
$l_galaxy_description[6] = "Uurimata Galaxy 6";
$l_galaxy_description[7] = "Uurimata Galaxy 7";
$l_galaxy_description[8] = "Uurimata Galaxy 8";
$l_galaxy_description[9] = "Uurimata Galaxy 9";
$l_galaxy_description[10] = "Uurimata Galaxy 10";

?>
