<?php
$l_help_title = "Kiirklahv Abi";
$l_help_subtitle = "Järgmine Kiirklahvid käivitab järgmised käsud:";
$l_help_addtraderoute = "Lisa traderoutes";
$l_help_globalchat = "Globaalne Jututuba";
$l_help_beacon = "Märgutuli";
$l_help_genesisdevice = "Genesis Device";
$l_help_sectorgenesis = "Valdkond Genesis";
$l_help_devicemenu = "Seadme menüüs";
$l_help_SDreport = "Valdkond kaitseministeeriumi raport";
$l_help_Ewarp = "Avarii Warp";
$l_help_fullLRscan = "Terve kauglevi Scan";
$l_help_galaxymap = "Galaxy Kaart";
$l_help_localmap = "Kohalik Galaxy Kaart";

$l_help_IGB = "IGB";
$l_help_log = "Logi sisse";
$l_help_logout = "Välju";
$l_help_readmessages = "Loe Sõnumid";
$l_help_deploymines = "Deploy kaevandus";
$l_help_news = "Uudised";
$l_help_sectornotes = "Valdkond Märkused";
$l_help_options = "Valikud";
$l_help_planetreport = "Planet Aruanne";
$l_help_probemenu = "Probe Menüü";
$l_help_ranking = "Edetabelid";

$l_help_shipreport = "Laev Aruanne";
$l_help_sendmessage = "Saada sõnum";
$l_help_listTRroutes = "Nimekiri kaubateed";
$l_help_teamSD = "Team Sector keinojasi";
$l_help_3Dmap = "3D Galaxy Kaart";
$l_help_warpeditor = "Warp toimetajale";
$l_help_storeshipreport = "Salvestatud Laev Aruanne";
$l_help_dignitarymenu = "Aukandja Menüü";
$l_help_spymenu = "Spy Menüü";
$l_help_galaxylocalwindow = "Galaxy Kohalik (uus aken)";
?>
