<?php
$l_help_title = "Ajuda de tecles d&#39;accés directe";
$l_help_subtitle = "Les tecles següents s&#39;executaran els següents comandaments:";
$l_help_addtraderoute = "Afegir un traderoutes";
$l_help_globalchat = "Global Xat";
$l_help_beacon = "Far";
$l_help_genesisdevice = "Dispositiu Gènesi";
$l_help_sectorgenesis = "Sector de Gènesi";
$l_help_devicemenu = "Menú de dispositius";
$l_help_SDreport = "Informe del sector de defensa";
$l_help_Ewarp = "Emergència Warp";
$l_help_fullLRscan = "Ple de llarg abast Scan";
$l_help_galaxymap = "Galaxy Mapa";
$l_help_localmap = "Galaxy Mapa Local";

$l_help_IGB = "IGB";
$l_help_log = "Registrar-se";
$l_help_logout = "Tancar sessió";
$l_help_readmessages = "Llegir missatges";
$l_help_deploymines = "Implementar les mines";
$l_help_news = "Notícies";
$l_help_sectornotes = "Notes del Sector";
$l_help_options = "Opcions";
$l_help_planetreport = "Informe del Planeta";
$l_help_probemenu = "Menú Sonda";
$l_help_ranking = "Classificació";

$l_help_shipreport = "Informe del vaixell";
$l_help_sendmessage = "Enviar missatge";
$l_help_listTRroutes = "Llista de rutes Comercials";
$l_help_teamSD = "Equip de defensa del sector";
$l_help_3Dmap = "Mapa 3D Galaxy";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Emmagatzemats Ship Informe";
$l_help_dignitarymenu = "Dignatari Menú";
$l_help_spymenu = "Spy Menú";
$l_help_galaxylocalwindow = "Galaxy Local (nova finestra)";
?>
