<?php
$l_galaxy_description = "(matriz)";
$l_galaxy_description[1] = "A Via Láctea é a galáxia onde o planeta Terra e da Federação está localizado";
$l_galaxy_description[2] = "Inexplorada Galaxy 2";
$l_galaxy_description[3] = "Inexplorada Galaxy 3";
$l_galaxy_description[4] = "Inexplorada Galaxy 4";
$l_galaxy_description[5] = "Inexplorada 5 Galaxy";
$l_galaxy_description[6] = "Inexplorada Galaxy 6";
$l_galaxy_description[7] = "Inexplorada Galaxy 7";
$l_galaxy_description[8] = "Inexplorada Galaxy 8";
$l_galaxy_description[9] = "Inexplorada Galaxy 9";
$l_galaxy_description[10] = "Inexplorada Galaxy 10";

?>
