<?php
$l_help_title = "Ajuda Hotkey";
$l_help_subtitle = "As teclas de atalho a seguir execute os seguintes comandos:";
$l_help_addtraderoute = "Adicionar um traderoutes";
$l_help_globalchat = "Chat Global";
$l_help_beacon = "Farol";
$l_help_genesisdevice = "Dispositivo Genesis";
$l_help_sectorgenesis = "Setor Genesis";
$l_help_devicemenu = "Dispositivo Menu";
$l_help_SDreport = "Defesa Sector Report";
$l_help_Ewarp = "Emergência Warp";
$l_help_fullLRscan = "Full Scan de longo alcance";
$l_help_galaxymap = "Galaxy Mapa";
$l_help_localmap = "Local Galaxy Mapa";

$l_help_IGB = "IGB";
$l_help_log = "Entrar";
$l_help_logout = "Sair";
$l_help_readmessages = "Ler Mensagens";
$l_help_deploymines = "Implantar Minas";
$l_help_news = "Notícias";
$l_help_sectornotes = "Setor de Notas";
$l_help_options = "Opções";
$l_help_planetreport = "Relatório Planeta";
$l_help_probemenu = "Sonda Menu";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Envio Relatório";
$l_help_sendmessage = "Enviar mensagem";
$l_help_listTRroutes = "Lista de Rotas de Comércio";
$l_help_teamSD = "Defesas Team Setor";
$l_help_3Dmap = "3D Galaxy Mapa";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Armazenados Ship Report";
$l_help_dignitarymenu = "Dignitário Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy Local (nova janela)";
?>
