<?php
$l_help_title = "Ndihmë Hotkey";
$l_help_subtitle = "Hotkeys e mëposhtme do të ekzekutojë komandat e mëposhtme:";
$l_help_addtraderoute = "Shto një traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Fener";
$l_help_genesisdevice = "Device Zanafilla";
$l_help_sectorgenesis = "Sektori Zanafilla";
$l_help_devicemenu = "Device Menu";
$l_help_SDreport = "Sektori mbrojtjes Raporti";
$l_help_Ewarp = "Urgjencës Warp";
$l_help_fullLRscan = "Long Range Full Scan";
$l_help_galaxymap = "Galaxy Harta";
$l_help_localmap = "Lokale Galaxy Harta";

$l_help_IGB = "IGB";
$l_help_log = "Identifikohu";
$l_help_logout = "Logout";
$l_help_readmessages = "Lexo Messages";
$l_help_deploymines = "Vendosë Miniera";
$l_help_news = "Lajme";
$l_help_sectornotes = "Sektori Shenimet";
$l_help_options = "Options";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Hetim Menu";
$l_help_ranking = "Renditjen";

$l_help_shipreport = "Raporti anije";
$l_help_sendmessage = "Dërgo Mesazh";
$l_help_listTRroutes = "Lista e Tregtisë Rrugët";
$l_help_teamSD = "Team mbrojtëse Sektori";
$l_help_3Dmap = "3D Galaxy Harta";
$l_help_warpeditor = "Prish Editor";
$l_help_storeshipreport = "Raporti i ruajtur Ship";
$l_help_dignitarymenu = "Dignitary Menu";
$l_help_spymenu = "Spiun Menu";
$l_help_galaxylocalwindow = "Galaxy Lokale (new window)";
?>
