<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Milky Way është galaktikë ku planetit Tokë dhe Federata është e vendosur";
$l_galaxy_description[2] = "Pashkelur Galaxy 2";
$l_galaxy_description[3] = "Pashkelur Galaxy 3";
$l_galaxy_description[4] = "Pashkelur Galaxy 4";
$l_galaxy_description[5] = "Pashkelur Galaxy 5";
$l_galaxy_description[6] = "Pashkelur Galaxy 6";
$l_galaxy_description[7] = "Pashkelur Galaxy 7";
$l_galaxy_description[8] = "Pashkelur Galaxy 8";
$l_galaxy_description[9] = "Pashkelur Galaxy 9";
$l_galaxy_description[10] = "Pashkelur Galaxy 10";

?>
