<?php
$l_chf_youretreatback = "Ju tërheqje mbrapa për vendndodhjen tuaj të mëparshëm";
$l_chf_movefailed = "Move dështuar.";
$l_chf_thefightersdetectyou = "Luftëtarëve të zbuluar ju!";
$l_chf_therearetotalfightersindest = "Ka [chf_total_sector_fighters] UÇK-së në sektorin tuaj destinacion.";
$l_chf_youcanretreat = "<B>Tërheqje</b> - A do të kushtojë kthehet ekstra.";
$l_chf_go = "Shkoj";
$l_chf_inputrun = "<B>Sulmi dhe Run</b> - Ju bëni një sulm drejtuar rrufetë dhe tërheqje. Por ju mund të marrë disa dëme gjatë tërheqje.";
$l_chm_hehitminesinsector = "[chm_playerinfo_character_name] [chm_roll] minave në sektorin [chm_sector].";
$l_chm_youlostminedeflectors = "Ju humbur [chm_roll] deflectors minave.";
$l_chm_youlostallminedeflectors = "Ju ka humbur të gjitha deflectors tuaj minave.";
$l_chm_youhadnominedeflectors = "Ju nuk kishte deflectors minave.";
$l_chm_yourshieldshitforminesdmg = "Mburojat tuaja janë goditur për [chm_mines_left] dëme.";
$l_chm_yourshieldsaredown = "Mburojat tuaja janë poshtë!";
$l_chm_youlostallyourshields = "Ju ka humbur të gjitha mburojat tuaja!";
$l_chm_yourarmorhitforminesdmg = "Forca të blinduara juaj është goditur për [chm_mines_left] dëme.";
$l_chm_yourhullisbreached = "Byk juaj është shkelur!";
$l_chm_hewasdestroyedbyyourmines = "[chm_playerinfo_character_name] u shkatërrua nga minat tuaja në sektorin [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Anija juaj është shkatërruar!";
$l_chm_luckescapepod = "Për fat të mirë ju keni një mbulesë shpëtuar!";

$l_chm_yourdeflectormalf1 = "Mine reflektor nisjen e ka funksiononin mirë sistemi.";
$l_chm_yourdeflectormalf2 = "Ju keni qenë vetëm në gjendje për të nisur";
$l_chm_yourdeflectormalf3 = "qind e deflectors tuaj minave.";
$l_chm_enemytorpfailshields = "nuk ka nisur asnjë silurët kundër mburoja juaj.";
$l_chm_enemytorpfailarmor = "nuk ka nisur asnjë silurët kundër forca të blinduara tuaj.";

$l_chm_minemalf1 = "Miniera armik të funksiononin mirë.";
$l_chm_minemalf2 = "Vetëm";
$l_chm_minemalf3 = "qind e minierave sulmuar gjetur anije tuaj.";

$l_chm_youhitsomemines = "Ju hit [chm_roll] mina nga [total_mines] mina!";
$l_chm_yourdeflectormalf2a = "Ju keni qenë vetëm në gjendje të fillojë [deflectors] qind e deflectors tuaj minave.";
$l_chm_mines_destroyed = "[number] i [target] minierat janë shkatërruar!";
$l_chm_mine_deflectors_left = "Ju keni [number] deflectors minë e mbetur.";
$l_chm_mines_left = "Ka [number] minat e mbetura dhe ata janë të ndikojnë mbi armaturën tuaj!";
$l_chm_minemalf2a = "Vetëm [deflectors] qind e minierave sulmuar gjetur anije tuaj.";
$l_chm_mines_exhausted = "[player] Miniera shteruar!";
$l_chm_armor_left = "Ju keni [number] pikat forca të blinduara u nis!";

$l_chf_therearetotalminesindest = "Ka [chf_total_sector_mines] minave në sektorin tuaj destinacion.";
$l_chf_inputfight = "<B>Fight</b> - Ju duhet të mposhtur të gjitha mbrojtjet për të hyrë në sektor.";
$l_chf_inputcloak = "<B>Mantel</b> - Përdorni pajisjen tuaj cloaking dhe të përpiqemi për të shmangur mbrojtëse.";
?>
