<?php
$l_chf_youretreatback    = "Retrocedes a tu posición anterior.";
$l_chf_movefailed        = "Movimiento fallido.";
$l_chf_thefightersdetectyou     = "¡Los cazas te detectaron!";
$l_chf_therearetotalfightersindest      = "Hay [chf_total_sector_fighters] cazas en el sector de destino.";
$l_chf_youcanretreat     = "<B>Retroceder</B> - Te costará un turno extra.";
$l_chf_go                = "Adelante";
$l_chf_inputrun = "<B>Atacar y correr</b> - Puedes hacer una vuelta de ataque relámpago y de retiro. Pero usted puede tomar algún daño durante el retiro.";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] chocó con  [chm_roll] minas en el sector [chm_sector].";
$l_chm_youlostminedeflectors    = "Perdiste [chm_roll] deflectores de minas.";
$l_chm_youlostallminedeflectors = "Perdiste todos tus deflectores de minas.";
$l_chm_youhadnominedeflectors  = "No tienes deflectores de minas.";
$l_chm_yourshieldshitforminesdmg        = "Tus escudos han sido alcanzados en [chm_mines_left] puntos.";
$l_chm_yourshieldsaredown       = "¡Tus escudos están desactivados!";
$l_chm_youlostallyourshields    = "¡Perdiste todos tus escudos!";
$l_chm_yourarmorhitforminesdmg  = "Tu blindaje ha sido alcanzado en [chm_mines_left] puntos.";
$l_chm_yourhullisbreached       = "¡Se ha abierto brecha en tu casco!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] fue destruido por tus minas en el sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "¡Tu nave ha sido destruida!";
$l_chm_luckescapepod     = "¡Afortunadamente tienes una cápsula de escape!";

$l_chm_yourdeflectormalf1 = "De Minas Deflector sistema de lanzamiento no ha funcionado correctamente.";
$l_chm_yourdeflectormalf2 = "Usted sólo han sido capaces de lanzar";
$l_chm_yourdeflectormalf3 = "por ciento de su deflectores de minas.";
$l_chm_enemytorpfailshields = "no ha lanzado torpedos contra sus escudos.";
$l_chm_enemytorpfailarmor = "no ha lanzado torpedos en contra de su armadura.";

$l_chm_minemalf1 = "Las minas enemigas han funcionado correctamente.";
$l_chm_minemalf2 = "Solamente";
$l_chm_minemalf3		 = " percent of the mines attcking found your ship.";

$l_chm_youhitsomemines = "Usted golpea [chm_roll] minas de [total_mines] minas!";
$l_chm_yourdeflectormalf2a = "Usted sólo han sido capaces de lanzar [deflectors] por ciento de su deflectores de minas.";
$l_chm_mines_destroyed = "[number] de [target] minas han sido destruidas!";
$l_chm_mine_deflectors_left = "Usted tiene [number] deflectores de minas a la izquierda.";
$l_chm_mines_left = "Hay [number] de las minas de la izquierda y que inciden en su armadura!";
$l_chm_minemalf2a = "Sólo [deflectors] por ciento de las minas de atacar a encontrar su barco.";
$l_chm_mines_exhausted = "[player] minas agotadas!";
$l_chm_armor_left = "Usted tiene [number] de los puntos de armadura de la izquierda!";

$l_chf_therearetotalminesindest = "Hay [chf_total_sector_mines] minas en su sector de destino.";
$l_chf_inputfight = "<B>Fight</b> - Debes derrotar a todos los defensas para entrar en el sector.";
$l_chf_inputcloak = "<B>Capa</b> - Utiliza tu dispositivo de invisibilidad y tratar de evitar las defensas.";
?>
