<?php
$l_help_title = "Ayuda de teclas de acceso directo";
$l_help_subtitle = "Las teclas siguientes se ejecutarán los siguientes comandos:";
$l_help_addtraderoute = "Añadir un traderoutes";
$l_help_globalchat = "Mundial Chat";
$l_help_beacon = "Faro";
$l_help_genesisdevice = "Dispositivo Génesis";
$l_help_sectorgenesis = "Sector de Génesis";
$l_help_devicemenu = "Menú de dispositivos";
$l_help_SDreport = "Informe del sector de defensa";
$l_help_Ewarp = "Emergencia Warp";
$l_help_fullLRscan = "Lleno de largo alcance Scan";
$l_help_galaxymap = "Galaxy Mapa";
$l_help_localmap = "Galaxy Mapa Local";

$l_help_IGB = "IGB";
$l_help_log = "Registrarse";
$l_help_logout = "Cerrar sesión";
$l_help_readmessages = "Leer mensajes";
$l_help_deploymines = "Implementar las minas";
$l_help_news = "Noticias";
$l_help_sectornotes = "Notas del Sector";
$l_help_options = "Opciones";
$l_help_planetreport = "Informe del Planeta";
$l_help_probemenu = "Menú Sonda";
$l_help_ranking = "Clasificación";

$l_help_shipreport = "Informe del buque";
$l_help_sendmessage = "Enviar mensaje";
$l_help_listTRroutes = "Lista de Rutas Comerciales";
$l_help_teamSD = "Equipo de defensa del sector";
$l_help_3Dmap = "Mapa 3D Galaxy";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Almacenados Ship Informe";
$l_help_dignitarymenu = "Dignatario Menú";
$l_help_spymenu = "Spy Menú";
$l_help_galaxylocalwindow = "Galaxy Local (nueva ventana)";
?>
