<?php
$l_help_title = "Pikanäppäin Ohje";
$l_help_subtitle = "Seuraavat Hotkeys tulee suorittaa seuraavat komennot:";
$l_help_addtraderoute = "Lisää traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Majakka";
$l_help_genesisdevice = "Genesiksen Device";
$l_help_sectorgenesis = "Alan Genesis";
$l_help_devicemenu = "Laitteen valikossa";
$l_help_SDreport = "Alan Defense Report";
$l_help_Ewarp = "Emergency Warp";
$l_help_fullLRscan = "Koko Long Range Scan";
$l_help_galaxymap = "Galaxy Kartta";
$l_help_localmap = "Paikalliset Galaxy Kartta";

$l_help_IGB = "IGB";
$l_help_log = "Lokin";
$l_help_logout = "Uloskirjautumista";
$l_help_readmessages = "Lue viestit";
$l_help_deploymines = "Deploy Mines";
$l_help_news = "Uutisia";
$l_help_sectornotes = "Alan Notes";
$l_help_options = "Valinnat";
$l_help_planetreport = "Planet Raportti";
$l_help_probemenu = "Probe Valikko";
$l_help_ranking = "Sijoituslista";

$l_help_shipreport = "Laiva Raportti";
$l_help_sendmessage = "Lähetä viesti";
$l_help_listTRroutes = "Luettelo Trade Routes";
$l_help_teamSD = "Team Sector puolustuksemme";
$l_help_3Dmap = "3D Galaxy Kartta";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Tallennettu Ship Raportti";
$l_help_dignitarymenu = "Arvohenkilö Valikko";
$l_help_spymenu = "Spy Valikko";
$l_help_galaxylocalwindow = "Galaxy Paikalliset (uusi ikkuna)";
?>
