<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Linnunrata on galaksi, jossa maapallon ja Federation sijaitsee";
$l_galaxy_description[2] = "Tutkimaton Galaxy 2";
$l_galaxy_description[3] = "Tutkimaton Galaxy 3";
$l_galaxy_description[4] = "Tutkimaton Galaxy 4";
$l_galaxy_description[5] = "Tutkimaton Galaxy 5";
$l_galaxy_description[6] = "Tutkimaton Galaxy 6";
$l_galaxy_description[7] = "Tutkimaton Galaxy 7";
$l_galaxy_description[8] = "Tutkimaton Galaxy 8";
$l_galaxy_description[9] = "Tutkimaton Galaxy 9";
$l_galaxy_description[10] = "Tutkimaton Galaxy 10";

?>
