<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Melkeveien er galaksen hvor planeten Jorden og Føderasjonen er lokalisert";
$l_galaxy_description[2] = "Uutforskede Galaxy 2";
$l_galaxy_description[3] = "Uutforskede Galaxy 3";
$l_galaxy_description[4] = "Uutforskede Galaxy 4";
$l_galaxy_description[5] = "Uutforskede Galaxy 5";
$l_galaxy_description[6] = "Uutforskede Galaxy 6";
$l_galaxy_description[7] = "Uutforskede Galaxy 7";
$l_galaxy_description[8] = "Uutforskede Galaxy 8";
$l_galaxy_description[9] = "Uutforskede Galaxy 9";
$l_galaxy_description[10] = "Uutforskede Galaxy 10";

?>
