<?php
$l_sn_title = "Sector Notes";
$l_sn_pntitle = "Sektorer med Personal Notes";
$l_sn_tntitle = "Sektorer med Team Notes";
$l_sn_psntitle = "Personlig Sector Notes";
$l_sn_tsntitle = "Team Sector Notes";
$l_sn_editnote = "Rediger Sector Merk:";
$l_sn_deleteedit = "";
$l_sn_addnote = "Legg Sector Merk:";
$l_sn_list = "Liste Sektorer Notes";
$l_sn_listts = "Liste Sektorer med Team Notes";
$l_sn_addteam = "Legg Team";
$l_sn_deleteteam = "Slett Team";
$l_sn_delete = "Slette";
$l_sn_saveteam = "Lagre Team";
$l_sn_deletepersonal = "Slett Personal";
$l_sn_addpersonal = "Legg Personal";
$l_sn_savepersonal = "Lagre Personal";
$l_sn_editpersonal = "Rediger Personlig";
$l_sn_editteam = "Rediger Team";

$l_sn_hdsector = "Sector";
$l_sn_hdtype = "Type";
$l_sn_hdowner = "Eier / Team";
$l_sn_hdplanets = "Planeter";
$l_sn_hdport = "Port";
$l_sn_hdfighters = "Fighters";
$l_sn_hdmines = "Mines";
$l_sn_hdscanfrom = "Scan Fra";
$l_sn_hddetail = "Detalj";
$l_sn_hddate = "Date / Time";
$l_sn_hddelete = "Slette";
$l_sn_hdteam = "Team";
$l_sn_view = "Utsikt";
$l_sn_no = "Nei";
$l_sn_yes = "Ja";
$l_sn_nonotes = "Ingen sektor Notes Found";

$l_sn_search = "Søke";
$l_sn_ally = "Ally";
$l_sn_base = "Base";
$l_sn_enemy = "Enemy";
$l_sn_port = "Port";
$l_sn_teambase = "Team Base";
$l_sn_minefield = "Minefelt";
$l_sn_sg_entry = "SG Entry";
$l_sn_spysector = "Spy sektor";
$l_sn_indy = "Indy";
$l_sn_notedate = "Dato";

?>
