<?php
$l_help_title = "Hurtigtast Hjelp";
$l_help_subtitle = "Følgende Hurtigtaster vil utføre følgende kommandoer:";
$l_help_addtraderoute = "Legg til en traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Beacon";
$l_help_genesisdevice = "Genesis Device";
$l_help_sectorgenesis = "Sector Genesis";
$l_help_devicemenu = "Device Menu";
$l_help_SDreport = "Sector forsvar Report";
$l_help_Ewarp = "Emergency Warp";
$l_help_fullLRscan = "Full Long Range Scan";
$l_help_galaxymap = "Galaxy Kart";
$l_help_localmap = "Lokale Galaxy Kart";

$l_help_IGB = "IGB";
$l_help_log = "Logg";
$l_help_logout = "Logg ut";
$l_help_readmessages = "Les Meldinger";
$l_help_deploymines = "Deploy Mines";
$l_help_news = "Nyheter";
$l_help_sectornotes = "Sector Notes";
$l_help_options = "Valg";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Probe Meny";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Ship Rapport";
$l_help_sendmessage = "Send melding";
$l_help_listTRroutes = "Liste handelsruter";
$l_help_teamSD = "Team Sector forsvar";
$l_help_3Dmap = "3D Galaxy Kart";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Lagrede Ship Report";
$l_help_dignitarymenu = "Herre Meny";
$l_help_spymenu = "Spy Meny";
$l_help_galaxylocalwindow = "Galaxy Lokal (nytt vindu)";
?>
