<?php
$l_help_title = "Hotkey-Hilfe";
$l_help_subtitle = "Die folgenden Tastenkombinationen werden die folgenden Befehle aus:";
$l_help_addtraderoute = "Fügen Sie einen traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Leuchtfeuer";
$l_help_genesisdevice = "Genesis Device";
$l_help_sectorgenesis = "Sector Genesis";
$l_help_devicemenu = "Device-Menü";
$l_help_SDreport = "Sector Defense Report";
$l_help_Ewarp = "Emergency Warp";
$l_help_fullLRscan = "Ausführliche Long Range Scan";
$l_help_galaxymap = "Galaxy Karte";
$l_help_localmap = "Lokale Galaxy Karte";

$l_help_IGB = "IGB";
$l_help_log = "Anmelden";
$l_help_logout = "Logout";
$l_help_readmessages = "Lesen Sie Nachrichten";
$l_help_deploymines = "Deploy Mines";
$l_help_news = "Nachrichten";
$l_help_sectornotes = "Sector Notes";
$l_help_options = "Optionen";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Probe-Menü";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Ship Bericht";
$l_help_sendmessage = "Nachricht senden";
$l_help_listTRroutes = "Liste Handelsrouten";
$l_help_teamSD = "Team Sektor Verteidigung";
$l_help_3Dmap = "Galaxy 3D-Karte";
$l_help_warpeditor = "Warp-Editor";
$l_help_storeshipreport = "Gespeicherte Schiff Bericht";
$l_help_dignitarymenu = "Würdenträger Menü";
$l_help_spymenu = "Spy-Menü";
$l_help_galaxylocalwindow = "Galaxy Lokal (neues Fenster)";
?>
