<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Die Milchstraße ist die Galaxie, in denen die Erde und der Föderation liegt";
$l_galaxy_description[2] = "Unexplored Galaxy 2";
$l_galaxy_description[3] = "Unexplored Galaxy 3";
$l_galaxy_description[4] = "Unexplored Galaxy 4";
$l_galaxy_description[5] = "Unexplored Galaxy 5";
$l_galaxy_description[6] = "Unexplored Galaxy 6";
$l_galaxy_description[7] = "Unexplored Galaxy 7";
$l_galaxy_description[8] = "Unexplored Galaxy 8";
$l_galaxy_description[9] = "Unexplored Galaxy 9";
$l_galaxy_description[10] = "Unexplored Galaxy 10";

?>
