<?php
$l_shipyard_title        = "Werft";
$l_planet = "Planet";
$l_ship_welcome = "Willkommen in der Werft der Planetary. Wir bieten zur Zeit diese Modelle zum Verkauf an.";
$l_ship_class = "Klasse";
$l_ship_properties = "Klassen-Eigenschaften";
$l_ship_current = "aktuell";
$l_ship_outstorage = "ausverkauft";
$l_ship_storagecost = "Lagerkosten";
///////////////////////////////////////
$l_ship_storagewarn = "Wenn nehmen Sie Ihren Pioneer aus der Lagerung verlieren Sie die von Ihnen waren auf Ihre erste Schiff Verwertungsnachweis ausgestellt.";
///////////////////////////////////////
$l_ship_levels = "Schiffsteile Levels";
$l_ship_min = "Min.";
$l_ship_max = "Max";
$l_ship_price = "Preis";
$l_ship_turns = "Turns für den Bau";
$l_ship_purchase = "Kaufen";
$l_ship_stored = "Gespeicherte";
$l_ship_basehull = "Base Rumpf:";

$l_ship_averagemaxtech = "Durchschnitt Maximum Tech Level:";
$l_ship_averagenormaltech = "Durchschnittliche Normal Tech Level:";
$l_ship_averagecurrenttech = "Durchschnittliche Aktuelle Tech Level:";
$l_ship_nostoreteamplanet = "Sie können keine ein Schiff auf einem Planeten Team.";

$l_ship2_buytitle        = "Neues Schiff kaufen";
$l_ship2_storetitle        = "Werft Zwischenlager";
$l_ship2_wrongclass        = "Falsche Schiffsklasse angegeben";
$l_ship2_buying        = "Sie kaufen:";
$l_ship2_tradein        = "Handeln In:";
$l_ship2_value        = "Aktueller Schiffswert:";
$l_ship2_newvalue        = "Neuer Schiffswert:";
$l_ship2_totalcost        = "Gesamtkosten:";
$l_ship2_nomoney        = "Sie haben nicht genügend Credits, dieses Schiff zu kaufen.";
$l_ship2_purchase        = "Kaufen";
$l_ship2_buynstore        = "Neues Schiff kaufen und altes einlagern";
$l_ship2_nomoney2        = "Sie haben nicht genügend Credits, diese Transaktion durch zuführen.";
$l_ship2_paystorage = "Ihr haben Ihr Schiff aus dem Lager entfernt.";
$l_ship2_turns        = "Sie benötigen mindestens [turns] Turns um diese Aktion durch zuführen";
$l_ship2_error        = "Interner Error. Schiffsklasse konnte nicht gefunden werden.";
$l_ship2_owned        = "YSie besitzen diesen Schiffstyp bereits.";
$l_ship2_shipbought        = "Sie haben gerade ein neues Schiff gekauft!";
?>
