<?php
$l_help_title = "Hotkey Help";
$l_help_subtitle = "The following Hotkeys will execute the following commands:";
$l_help_addtraderoute = "Add a traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Beacon";
$l_help_genesisdevice = "Genesis Device";
$l_help_sectorgenesis = "Sector Genesis";
$l_help_devicemenu = "Device Menu";
$l_help_SDreport = "Sector defense Report";
$l_help_Ewarp = "Emergency Warp";
$l_help_fullLRscan = "Full Long Range Scan";
$l_help_galaxymap = "Galaxy Map";
$l_help_localmap = "Local Galaxy Map";

$l_help_IGB = "IGB";
$l_help_log = "Log";
$l_help_logout = "Logout";
$l_help_readmessages = "Read Messages";
$l_help_deploymines = "Deploy Mines";
$l_help_news = "News";
$l_help_sectornotes = "Sector Notes";
$l_help_options = "Options";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Probe Menu";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Ship Report";
$l_help_sendmessage = "Send Message";
$l_help_listTRroutes = "List Trade Routes";
$l_help_teamSD = "Team Sector defenses";
$l_help_3Dmap = "3D Galaxy Map";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Stored Ship Report";
$l_help_dignitarymenu = "Dignitary Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy Local (new window)";
?>