<?php
$l_help_title = "Hotkey Bantuan";
$l_help_subtitle = "Hotkeys berikut akan menjalankan perintah berikut:";
$l_help_addtraderoute = "Tambah traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Suar";
$l_help_genesisdevice = "Kejadian Device";
$l_help_sectorgenesis = "Sektor Kejadian";
$l_help_devicemenu = "Menu perangkat";
$l_help_SDreport = "Sektor pertahanan Laporan";
$l_help_Ewarp = "Warp darurat";
$l_help_fullLRscan = "Kendali Long Range Scan";
$l_help_galaxymap = "Peta galaksi";
$l_help_localmap = "Peta Galaxy Lokal";

$l_help_IGB = "IGB";
$l_help_log = "Masuk log";
$l_help_logout = "Logout";
$l_help_readmessages = "Baca Pesan";
$l_help_deploymines = "Menyebarkan Pertambangan";
$l_help_news = "Berita";
$l_help_sectornotes = "Catatan Sektor";
$l_help_options = "Pilihan";
$l_help_planetreport = "Planet Laporan";
$l_help_probemenu = "Probe Menu";
$l_help_ranking = "Tingkatan";

$l_help_shipreport = "Kapal Laporan";
$l_help_sendmessage = "Kirim Pesan";
$l_help_listTRroutes = "Daftar Rute Perdagangan";
$l_help_teamSD = "Tim Sektor pertahanan";
$l_help_3Dmap = "3D Peta Galaxy";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Kapal disimpan Laporan";
$l_help_dignitarymenu = "Pembesar Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy Lokal (jendela baru)";
?>
