<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Bima Sakti adalah galaksi dimana planet Bumi dan Federasi Terletak";
$l_galaxy_description[2] = "Belum diselidiki Galaxy 2";
$l_galaxy_description[3] = "Belum diselidiki Galaxy 3";
$l_galaxy_description[4] = "Belum diselidiki Galaxy 4";
$l_galaxy_description[5] = "Belum diselidiki Galaxy 5";
$l_galaxy_description[6] = "Belum diselidiki Galaxy 6";
$l_galaxy_description[7] = "Galaxy belum diselidiki 7";
$l_galaxy_description[8] = "8 Galaxy belum diselidiki";
$l_galaxy_description[9] = "Galaxy belum diselidiki 9";
$l_galaxy_description[10] = "10 Galaxy belum diselidiki";

?>
