<?php

// Confirmed common to multiple files:

$game_charset = "ISO-8859-1";

$l_zname[1] = "Unchartered ruang";
$l_zname[2] = "Federasi ruang";
$l_zname[3] = "Aliansi ruang";
$l_zname[4] = "Zona Perang";

$l_nova = "Bintang yg baru";
$l_nova = "Nova Bom";
$l_lssd = "Kapal terakhir melihat perangkat";
$l_lss = "Kapal terakhir terlihat di sektor ini";
$l_galaxy = "Galaksi";

// Common to : warpedit 1-3.php

$l_warp_title = "Gunakan Warp Editor";
$l_warp_turn = "Anda memerlukan setidaknya satu giliran untuk menggunakan warp editor.";
$l_warp_none = "Anda tidak memiliki editor warp.";
$l_warp_forbid = "Menggunakan Warp Editor di sektor ini tidak diijinkan.";
$l_swarp_forbid = "Menggunakan Editor Warp ke atau dari SG sektor tidak diijinkan.";
$l_warp_nosector = "Sektor tidak ada.";

// Not yet confirmed common to multiple files:

$l_yes = "Ya";
$l_no = "Tidak";
$l_here = "di sini";
$l_submit = "Menyerahkan";
$l_reset = "Reset";
$l_all = "Semua";
$l_max = "Max";

$l_trade = "Perdagangan";
$l_ore = "Bijih";
$l_commodity = "Komoditi";
$l_commodities = "Komoditi";
$l_organics = "Organik";
$l_goods = "Barang";
$l_energy = "Energi";
$l_colonists = "Koloni";
$l_credits = "Kredit";
$l_units = "unit";
$l_special = "Khusus";
$l_upgrade_ports = "Upgrade";
$l_device_ports = "Perangkat";
$l_spacedock = "Spacedock";
$l_casino = "Kasino";
$l_dig = "Tokoh";
$l_spy = "Spies";
$l_wormhole = "Lubang ulat";

$l_cargo = "";
$l_fighters = "Fighters";
$l_mines = "Tambang";
$l_torps = "Torpedo";

$l_none = "Tak satupun";
$l_unnamed = "Tanpa Nama";
$l_name = "Nama";
$l_unowned = "Unowned";
$l_unknown = "Unknown";
$l_clickme = "Klik di sini";
$l_player = "Player";
$l_ship = "Mengirim";
$l_ships = "Kapal";
$l_set = "mengatur";
$l_realspace = "Realspace";
$l_armorpts = "Armor poin";
$l_links = "Link";
$l_login_email = "Alamat E-mail:";
$l_add = "Tambah";
$l_teamforum = "Tim Forum";
$l_teamships = "Tim Kapal";
$l_tutorial = "Tutorial / Bantuan";
$l_avatar = "Avatar";
$l_teamicon = "Tim Icon";
$l_debris = "Puing";
$l_localmap = "Peta";
$l_arm_weap = "Armor &amp; Senjata";
$l_3dmap = "3D Peta Galaxy";

$l_sectormissile = "Sektor Missile";
$l_spacebeacon = "";
$l_spaceprobes = "Space Probe";
$l_warpeditors = "Warp Editor";
$l_genesistorps = "Kejadian Torpedoes";
$l_sgtorps = "SG Torpedoes";
$l_minesfighters = "Tambang / Fighters";
$l_ewarp = "Warp darurat";
$l_reports = "Laporan";
$l_shipinfo = "Info Kapal";
$l_sectornotes = "Catatan Sektor";
$l_maps = "Peta";
$l_messages = "Pesan";
$l_shiptype = "Jenis Kapal";
$l_help = "Membantu";
$l_rank = "Pangkat";

$l_teamplanets = "Tim Planet";
$l_teamdefenses = "Tim pertahanan";
$l_planetstatus = "Planet Status";
$l_planetdefenses = "Planet pertahanan";
$l_changeproduction = "Ubah Produksi";
$l_galacticarm = "Galactic Lengan";

$l_armor = "Baja";
$l_news_none = "Maaf, tidak ada berita hari ini.";

$l_ranks_good = "Baik";
$l_ranks_evil = "Jahat";
$l_ranks_neutral = "Netral";

$l_global_mmenu          ="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin         ="Click <A HREF=index.php>here</A> to return to the login screen.";
$l_global_needlogin      ="You need to log in, click <A HREF=index.php>here</A>.";
$l_global_died           ="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone = "Zona sekarang adalah Zona Perang!";
$l_global_nzone = "Zona adalah zona netral.";
$l_global_team = "Zona sekarang menjadi milik tim";
$l_global_player = "Zona sekarang menjadi milik pemain";
$l_global_nochange = "Zona kepemilikan tidak berubah";
$l_insignia[0] = "1c.png";
$l_insignia[1] = "2c.png";
$l_insignia[2] = "3c.png";
$l_insignia[3] = "4c.png";
$l_insignia[4] = "o-1.png";
$l_insignia[5] = "o-2.png";
$l_insignia[6] = "o-3.png";
$l_insignia[7] = "o-4.png";
$l_insignia[8] = "o-5.png";
$l_insignia[9] = "o-6.png";
$l_insignia[10] = "o-7.png";
$l_insignia[11] = "o-8.png";
$l_insignia[12] = "o-9.png";
$l_insignia[13] = "o-10.png";
$l_insignia[14] = "o-11.png";
$l_insignia[15] = "o-12.png";
$l_insignia[16] = "o-13.png";
$l_insignia[17] = "o-14.png";
$l_insignia[18] = "o-15.png";
$l_insignia[19] = "o-16.png";

$l_insignia_name[0] = "Merekrut Spaceman";
$l_insignia_name[1] = "Spaceman Magang";
$l_insignia_name[2] = "Angkasawan";
$l_insignia_name[3] = "Petty Officer Kelas Ketiga";
$l_insignia_name[4] = "Petty Officer Kelas Kedua";
$l_insignia_name[5] = "Petty Officer First Class";
$l_insignia_name[6] = "Chief Petty Officer";
$l_insignia_name[7] = "Chief Petty Officer Senior";
$l_insignia_name[8] = "Master Chief Petty Officer";
$l_insignia_name[9] = "Bendera";
$l_insignia_name[10] = "Letnan Junior Grade";
$l_insignia_name[11] = "Letnan";
$l_insignia_name[12] = "Letnan Komandan";
$l_insignia_name[13] = "Komandan";
$l_insignia_name[14] = "Kapten";
$l_insignia_name[15] = "Laksamana Muda (bagian bawah)";
$l_insignia_name[16] = "Laksamana Muda (atas setengah)";
$l_insignia_name[17] = "Laksamana";
$l_insignia_name[18] = "Laksamana";
$l_insignia_name[18] = "Laksamana";

$l_main_title = "Menu";
$l_main_warpto = "Warp untuk";
$l_main_autoroute = "Autoroute untuk";
$l_main_rs_to = "RSMove untuk";
$l_main_other = "Lain";
$l_main_shipyard1 = "Galangan";
$l_main_shipyard2 = "Mengakses";
$l_traderoutes = "Rute Perdagangan";
$l_trade_control = "Perdagangan Control";
$l_youhave = "Anda telah";
$l_turns_used = "Ternyata digunakan:";
$l_turns_have = "Ternyata tersedia:";
$l_score = "Score:";
$l_sector = "Sektor";
$l_help = "Membantu";
$l_faq = "FAQ";
$l_feedback = "Umpan balik";
$l_forums = "Forum";
$l_logout = "Logout";
$l_commands = "Perintah";
$l_command_no = "Perintah tidak tersedia.";
$l_devices = "Perangkat";
$l_planets = "Planet";
$l_log = "Masuk log";
$l_sector_def = "Sektor pertahanan";
$l_defense = "Pertahanan";
$l_read_msg = "Baca Pesan";
$l_send_msg = "Kirim Pesan";
$l_rankings = "Tingkatan";
$l_teams = "Tim";
$l_ohno = "Merusak diri";
$l_options = "Pilihan";
$l_navcomp = "Nav Komputer";
$l_incompletemove = "Anda belum menyelesaikan langkah sebelumnya.";
$l_clicktocontinue = "Klik disini untuk melanjutkan";
$l_toplanetmenu = "untuk pergi ke planet menu.";
$l_nonexistant_pl = "Pada yang tidak ada planet???";
$l_abord = ", Di atas kapal";
$l_messages_wait = "Pesan yang menunggu untuk Anda.";
$l_no_warplink = "Tidak ada warp link";
$l_scan = "scan";
$l_fullscan = "";
$l_port = "Pelabuhan";
$l_tradingport = "Pelabuhan dagang";
$l_planet_in_sec = "Planet dalam sektor";
$l_ships_in_sec = "Kapal-kapal lain di sektor";
$l_sector_0 = "Ada begitu banyak lalu lintas di Sol bahwa Anda bahkan tidak dapat mengisolasi kapal lain!";
$l_map = "Peta";
$l_probe = "Probe";
$l_onboard = "onboard yang";
$l_classship = "kelas kapal";
$l_traveled = "bepergian ke sektor";
$l_max_planets = "Habital maksimum planet";
$l_block_msg = "Blok Messages";
$l_sectorinfo = "Sektor Info";
$l_add_note = "Tambah Catatan";
$l_view_note = "Melihat";
$l_notes = "Catatan";
$l_global_limitreached = "Anda telah mencapai batas untuk jumlah waktu Anda diijinkan secara online setiap hari. Log in lagi besok setelah tengah malam.";
$l_onlinetimeleft = "Sisa Waktu:";
$l_planetmax = "Planet Maksimum:";
$l_storedshipreport = "Disimpan Kapal";
$l_global_chat = "Global Chat";
$l_team_chat = "Tim Chat";
$l_fedinfo = "Informasi federasi Port";
$l_team_shoutbox = "Team Shoutbox";
$l_lobby = "Trader&#39;s Lobby";

$l_common_prev = "Previous Page";
$l_common_next = "Next Page";
$l_common_totalpages = "Jumlah Halaman";
$l_common_selectpage = "Pilih Halaman:";
$l_common_page = "Halaman:";
$l_templatechange = "Apakah Anda ingin menyimpan Templat ini?";

$l_im_fed_bounty = "Federasi telah meletakkan karunia pada anda untuk menyerang seperti pemain peringkat rendah. Federasi akan menyerang kapal Anda secara teratur sampai Anda membayar kembali karunia Anda. Anda bisa melunasi karunia Anda setiap Upgrade Port atau Spacedock.";
$l_im_fed_bounty_title = "Federasi meletakkan karunia pada Anda!";
$l_im_alliance_bounty = "Aliansi telah meletakkan karunia pada anda untuk menyerang seperti pemain peringkat rendah. Aliansi akan menyerang kapal Anda secara teratur sampai Anda membayar kembali karunia Anda. Anda bisa melunasi karunia Anda setiap Upgrade Port atau Spacedock.";
$l_im_alliance_bounty_title = "Aliansi meletakkan karunia pada Anda!";
$l_instant_messages_waiting = "Anda telah [count] pesan yang menunggu untuk Anda.";

$l_home_planet = "Home Planet";

$l_hold_space_used = "Holds Terisi:";
$l_hold_space_free = "Holds Empty:";
$l_port_buys = "Port Buys:";
$l_port_sells = "Port Menjual:";
$l_port_quantity = "Quantity:";
$l_port_price = "Harga:";

$l_shoutbox = "Kotak Pesan";
$l_selectautoroute = "Pilih Autoroute";
$l_profiles = "Profil";
$l_public = "Umum?";
$l_RStolastsector = "Realspace to Last Sector";
$l_RSturns = "Ternyata Realspace";

$l_playeroutoftime = "Anda telah [time] menit per hari bermain game. Anda telah menggunakan seluruh waktu Anda untuk hari ini. Anda akan di Lobby Chat untuk [hours] jam dan [minutes] menit. Anda akan diizinkan untuk melanjutkan bermain ketika permainan me-reset waktu online untuk semua pemain.";

$l_casino_description = "Casino port semua dimiliki oleh Aliansi. Federasi tidak memiliki kontrol atas daerah-daerah tersebut. Anda dapat menemukan judi dan papan pesan Galaxy Wide disebut &quot;Den Penyelundup &#39;. Apa pun yang diposting di salah satu Den Penyelundup dapat dilihat di semua dens Penyelundup di mana saja dan di galaksi manapun.";
$l_upgrades_description = "Pelabuhan Upgrade adalah di mana Anda dapat membeli upgrade teknologi untuk kapal Anda sedang piloting.";
$l_device_description = "Pelabuhan Device adalah di mana Anda dapat membeli perangkat seperti Beacon, Spies, dll untuk kapal sedang Anda piloting.";
$l_spacedock_description = "Spacedocks adalah di mana Anda dapat memperbaiki kerusakan pada kapal Anda saat ini pilot.";
$l_none_description = "Sektor ini tidak berisi port.";
$l_infoport_description = "Info Federasi Port adalah tempat Anda dapat menemukan informasi berguna tentang bergerak di sekitar galaksi dan mengemudikan kapal Anda. pengumuman Berita dari Federasi akan diposting untuk semua orang untuk melihat di kali. Info Federasi Port selalu terletak di Sektor Sol.";

$l_autoroutelist = "Rute ke Sektor";
$l_mininavinfo = "Klik Sektor untuk menyimpan nama dalam Warp / kotak input Realspace. Klik W untuk menemukan Autoroute dan warp, Ke Realspace atau? untuk memeriksa Realspace bergantian.";

$l_noroutetosectortitle = "No Route";
$l_noroutetosectorbody = "Tidak dapat menemukan rute ke sektor.";

?>
