<?php
$l_help_title = "Hotkey Aiuto";
$l_help_subtitle = "Tasti di scelta rapida il seguente eseguire i seguenti comandi:";
$l_help_addtraderoute = "Aggiungi un traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Faro";
$l_help_genesisdevice = "Dispositivo Genesis";
$l_help_sectorgenesis = "Settore dei Genesis";
$l_help_devicemenu = "Menu Periferica";
$l_help_SDreport = "Settore difesa Report";
$l_help_Ewarp = "Emergenza Warp";
$l_help_fullLRscan = "Gamma completa di scansione lungo";
$l_help_galaxymap = "Galaxy Map";
$l_help_localmap = "Locali Galaxy Map";

$l_help_IGB = "IGB";
$l_help_log = "Entra";
$l_help_logout = "Logout";
$l_help_readmessages = "Leggi Messaggi";
$l_help_deploymines = "Distribuire Mines";
$l_help_news = "Notizie";
$l_help_sectornotes = "Settore Note";
$l_help_options = "Opzioni";
$l_help_planetreport = "Planet Report";
$l_help_probemenu = "Sonda Menu";
$l_help_ranking = "Classifiche";

$l_help_shipreport = "Nave Report";
$l_help_sendmessage = "Invia messaggio";
$l_help_listTRroutes = "Elenco Trade Routes";
$l_help_teamSD = "Il team del settore difesa";
$l_help_3Dmap = "Mappa 3D Galaxy";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Memorizzati Ship Report";
$l_help_dignitarymenu = "Dignitario Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy locale (nuova finestra)";
?>
