<?php
$l_shipyard_title        = "Hangar";
$l_planet                = "Pianeta";
$l_ship_welcome = "Benvenuti a questo Hangar della Planetary. Attualmente abbiamo queste navi disponibili per la vendita.";
$l_ship_class = "Classe";
$l_ship_properties = "Proprietà Classe";
$l_ship_current = "Attuale";
$l_ship_outstorage = "Ritira dal Deposito";
$l_ship_storagecost = "Costo Deposito";
$l_ship_storagewarn = "Una volta che ritiri la tua Pioneer dal Deposito, perderai quella che ti era stata data dopo la distruzione della tua nave.";
$l_ship_levels = "Livello Sistemi Nave";
$l_ship_min = "Min";
$l_ship_max = "Max";
$l_ship_price = "Prezzo";
$l_ship_turns = "Turni per costruirla";
$l_ship_purchase = "Acquista";
$l_ship_stored = "Memorizzati";
$l_ship_basehull = "Base dello scafo:";
$l_ship_nostoreteamplanet = "Non è possibile memorizzare una nave su un pianeta squadra.";

$l_ship_averagemaxtech = "Media Massimo Tech Level:";
$l_ship_averagenormaltech = "Media normale Tech Level:";
$l_ship_averagecurrenttech = "Media attuale Tech Level:";
$l_ship2_buytitle        = "Acquisto Nuova Nave";
$l_ship2_storetitle = "Cantiere Storage Facility";
$l_ship2_wrongclass        = "Errata classe di nave specificata";
$l_ship2_buying        = "Stai per comprare:";
$l_ship2_tradein        = "Vendi la vecchia nave:";
$l_ship2_value        = "Valore attuale della nave:";
$l_ship2_newvalue        = "Nuovo valore della nave:";
$l_ship2_totalcost        = "Costo totale:";
$l_ship2_nomoney        = "Non hai abbastanza crediti per comprare questa nave.";
$l_ship2_purchase        = "Acquista";
$l_ship2_buynstore        = "Compra una nuova nave, e metti in deposito quella vecchia";
$l_ship2_nomoney2        = "Non hai abbastanza crediti per completare quest'operazione.";
$l_ship2_paystorage = "Il tuo stato rimosso la vostra nave da deposito.";
$l_ship2_turns        = "Ti occorrono almeno [turns] turni per attuare questa operazione";
$l_ship2_error        = "Errore interno. Impossibile trovare la classe della nave.";
$l_ship2_owned        = "Già possiedi questo modello di nave.";
$l_ship2_shipbought        = "Hai appena acquistato una nuova nave!";

?>
