<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "La Via Lattea è la galassia in cui si trova il pianeta Terra e la Federazione";
$l_galaxy_description[2] = "Inesplorato Galaxy 2";
$l_galaxy_description[3] = "Inesplorato Galaxy 3";
$l_galaxy_description[4] = "Inesplorato Galaxy 4";
$l_galaxy_description[5] = "Inesplorato 5 Galaxy";
$l_galaxy_description[6] = "Inesplorato Galaxy 6";
$l_galaxy_description[7] = "Inesplorato Galaxy 7";
$l_galaxy_description[8] = "Inesplorato Galaxy 8";
$l_galaxy_description[9] = "Inesplorato Galaxy 9";
$l_galaxy_description[10] = "Inesplorato Galaxy 10";

?>
