<?php
$l_galaxy_description = "array ()";
$l_galaxy_description[1] = "Mælkevejen er galaksens hvor planeten Jorden og Føderationen er beliggende";
$l_galaxy_description[2] = "Uudforskede Galaxy 2";
$l_galaxy_description[3] = "Uudforskede Galaxy 3";
$l_galaxy_description[4] = "Uudforskede Galaxy 4";
$l_galaxy_description[5] = "Uudforskede Galaxy 5";
$l_galaxy_description[6] = "Uudforskede Galaxy 6";
$l_galaxy_description[7] = "Uudforskede Galaxy 7";
$l_galaxy_description[8] = "Uudforskede Galaxy 8";
$l_galaxy_description[9] = "Uudforskede Galaxy 9";
$l_galaxy_description[10] = "Uudforskede Galaxy 10";

?>
