<?php
$l_help_title = "Genvejstast Hjælp";
$l_help_subtitle = "Følgende genvejstaster vil udføre følgende kommandoer:";
$l_help_addtraderoute = "Tilføj en traderoutes";
$l_help_globalchat = "Global Chat";
$l_help_beacon = "Beacon";
$l_help_genesisdevice = "Genesis Device";
$l_help_sectorgenesis = "Sektor Genesis";
$l_help_devicemenu = "Device Menu";
$l_help_SDreport = "Sektor Defense Report";
$l_help_Ewarp = "Emergency Warp";
$l_help_fullLRscan = "Fuld Long Range Scan";
$l_help_galaxymap = "Galaxy Kort";
$l_help_localmap = "Lokale Galaxy Kort";

$l_help_IGB = "IGB";
$l_help_log = "Log";
$l_help_logout = "Log";
$l_help_readmessages = "Læs Beskeder";
$l_help_deploymines = "Deploy Mines";
$l_help_news = "Nyheder";
$l_help_sectornotes = "Sektor Noter";
$l_help_options = "Valg";
$l_help_planetreport = "Planet Rapport";
$l_help_probemenu = "Probe Menu";
$l_help_ranking = "Rankings";

$l_help_shipreport = "Ship Rapport";
$l_help_sendmessage = "Send besked";
$l_help_listTRroutes = "Liste Trade Routes";
$l_help_teamSD = "Team Sector forsvar";
$l_help_3Dmap = "3D Galaxy Kort";
$l_help_warpeditor = "Warp Editor";
$l_help_storeshipreport = "Lagrede Ship Report";
$l_help_dignitarymenu = "Dignitar Menu";
$l_help_spymenu = "Spy Menu";
$l_help_galaxylocalwindow = "Galaxy Lokale (nyt vindue)";
?>
